### PR TITLE
Django email backend metadata support. Closes #180

### LINKED ISSUE #180: Add metadata support for Django email backend
Hello,
We use this app with Django and need to send messages with metadata via `postmarker.django.EmailBackend`.
I seem to have figured out how to add this possibility and going to open a pull request soon.

* Follow-up on #63 and #168

### PR DESCRIPTION
**Pull request by avityk**
* Add metadata support to `postmarker.django.EmailBackend`
* Add test for email with metadata
* Update docs
* Fix `tox.ini`: specify versions of packages

### CODE REVIEW

**Comment by Stranger6667** [comment]
Hello @avityk !
Thank you for your contribution :) I will check it during today

**Comment by avityk** [comment]
Hello @Stranger6667 ! I see that some tests fail on CI due to missing python 3.4 interpreter. Does it require any action from me? I'm not really familiar with Travis CI :)
And if the code is OK, can we get it released soon please?

**Comment by Stranger6667** [comment]
Hej @avityk ! Yep, the code looks good to me, I will merge this PR and will deal with Python 3.4 on Travis :) Hopefully, will release a new version today

**Comment by avityk** [comment]
Thanks a lot!

**Comment by Stranger6667** [comment]
You're welcome :)

**Comment by Stranger6667** [comment]
Released on PyPI - https://pypi.org/project/postmarker/0.13.1/

Please, let me know in case of any issues with the new release

**Pull request merged**
