### PR TITLE
Handle error responses that do not contain JSON

### LINKED ISSUE #163: Handle responses that do not contain JSON
In certain cases, we've received responses from Postmark (or an intermediary server) that do not contain JSON. This causes `PostmarkClient.check_response` to raise a `ValueError` (originating [here](https://github.com/Stranger6667/postmarker/blob/0.12.0/postmarker/core.py#L139)).

The `ValueError` doesn't include any useful information. In my opinion, in cases where the JSON cannot be decoded to retrieve error information either a `ClientError` or the `HTTPError` should be raised.

### PR DESCRIPTION
**Pull request by micthiesen**
Closes #163

### CODE REVIEW

**Comment by Stranger6667** [comment]
Hej!
Thank you for your contribution! :) 

Could you give me some example of such payload from Postmark?

**Comment by micthiesen** [comment]
Hey np! I wasn't able to retrieve an example payload yet since the `ValueError` that was being raised didn't include much useful information.

Since our use case with Postmark is very simple, we're going to switch to us `requests` in our app. If it happens again I'll update this PR with what the response looks like. In the meantime feel free to close this.

**Comment by Stranger6667** [comment]
I believe, that the case is important indeed and I'm happy to merge it :) I'll take care about the testing later

**Comment by micthiesen** [comment]
Thanks for the quick release! Much appreciated.

**Comment by Stranger6667** [comment]
You're welcome :)

**Pull request merged**
